### ISSUE TITLE
How to limit the area to draw grass?

### ISSUE THREAD

**Issue by psociety** [Youssef-Afella/UnityURP-InfiniteGrassField#1]
TY FOR CREATING AND SHARING THIS!!

Is there a way to draw like a "polygon" where you want the grass to be?
I've checked the readme and the `InstancedIndirectGrassRenderer` component but i can't seem to find how/if it's possible.

**Comment by Youssef-Afella** [comment]
Can't really understand what do you mean with polygon ?
Do you mean changing the grass blades from a simple triangle to another mesh ?

**Comment by psociety** [comment]
No, no, i'm refering on how to limit where the grass appears. Think of having a terrain with a path and not wanting grass on the path, so you only mark some areas where the grass should appear.
Like:
![image](https://i0.wp.com/spatial-dev.guru/wp-content/uploads/2022/10/DrawHolesInOpenLayersPolygon.gif?fit=969%2C636&ssl=1)

**Comment by Youssef-Afella** [comment]
No it doesn't, not right now
Maybe i will expand it to do that later

**Comment by psociety** [comment]
cool! so right now there's no way to limit where the grass appears right? it will always be on all floors.

**Comment by Youssef-Afella** [comment]
No, and it will be exactly in the y=0 plane
